 
****************************************
Report : resources
Design : HT
Version: T-2022.03
Date   : Sun Apr 12 21:13:19 2026
****************************************


Resource Report for this hierarchy in file ../01_RTL/HT.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| add_x_1        | DW01_inc       | width=4    | add_30_S2 (HT.v:30)        |
| lte_x_4        | DW_cmp         | width=3    | lte_98 (HT.v:98)           |
| lte_x_5        | DW_cmp         | width=3    | lte_98_S2 (HT.v:98)        |
| lte_x_6        | DW_cmp         | width=3    | lte_99 (HT.v:99)           |
| lte_x_7        | DW_cmp         | width=3    | lte_99_S2 (HT.v:99)        |
| lte_x_8        | DW_cmp         | width=3    | lte_100 (HT.v:100)         |
| lte_x_9        | DW_cmp         | width=3    | lte_100_S2 (HT.v:100)      |
| lte_x_10       | DW_cmp         | width=3    | lte_101 (HT.v:101)         |
| lte_x_19       | DW_cmp         | width=8    | lte_122 (HT.v:122)         |
| lte_x_20       | DW_cmp         | width=8    | lte_122_S2 (HT.v:122)      |
| lte_x_21       | DW_cmp         | width=8    | lte_123 (HT.v:123)         |
| lte_x_22       | DW_cmp         | width=8    | lte_123_S2 (HT.v:123)      |
| lte_x_23       | DW_cmp         | width=8    | lte_124 (HT.v:124)         |
| lte_x_24       | DW_cmp         | width=8    | lte_124_S2 (HT.v:124)      |
| add_x_32       | DW01_add       | width=4    | add_139 (HT.v:139)         |
| lte_x_34       | DW_cmp         | width=9    | lte_143 (HT.v:143)         |
| lte_x_35       | DW_cmp         | width=9    | lte_143_S2 (HT.v:143)      |
| lte_x_36       | DW_cmp         | width=9    | lte_144 (HT.v:144)         |
| lte_x_37       | DW_cmp         | width=9    | lte_144_S2 (HT.v:144)      |
| lte_x_38       | DW_cmp         | width=9    | lte_145 (HT.v:145)         |
| add_x_45       | DW01_add       | width=6    | add_158 (HT.v:158)         |
| add_x_46       | DW01_add       | width=5    | add_159 (HT.v:159)         |
| lte_x_48       | DW_cmp         | width=10   | lte_163 (HT.v:163)         |
| lte_x_49       | DW_cmp         | width=10   | lte_163_S2 (HT.v:163)      |
| lte_x_50       | DW_cmp         | width=10   | lte_164 (HT.v:164)         |
| lte_x_51       | DW_cmp         | width=10   | lte_164_S2 (HT.v:164)      |
| lte_x_57       | DW_cmp         | width=10   | lte_181 (HT.v:181)         |
| lte_x_58       | DW_cmp         | width=10   | lte_181_S2 (HT.v:181)      |
| lte_x_59       | DW_cmp         | width=10   | lte_182 (HT.v:182)         |
| lte_x_64       | DW_cmp         | width=10   | lte_198 (HT.v:198)         |
| lte_x_65       | DW_cmp         | width=10   | lte_198_S2 (HT.v:198)      |
| lte_x_69       | DW_cmp         | width=10   | lte_213 (HT.v:213)         |
| eq_x_73        | DW_cmp         | width=4    | eq_248 (HT.v:248)          |
| eq_x_74        | DW_cmp         | width=4    | eq_253 (HT.v:253)          |
| eq_x_75        | DW_cmp         | width=4    | eq_248_I2 (HT.v:248)       |
| add_x_76       | DW01_inc       | width=2    | add_250_I2 (HT.v:250)      |
| eq_x_77        | DW_cmp         | width=4    | eq_253_I2 (HT.v:253)       |
| eq_x_78        | DW_cmp         | width=4    | eq_248_I3 (HT.v:248)       |
| add_x_79       | DW01_inc       | width=3    | add_250_I3 (HT.v:250)      |
| eq_x_80        | DW_cmp         | width=4    | eq_253_I3 (HT.v:253)       |
| eq_x_81        | DW_cmp         | width=4    | eq_248_I4 (HT.v:248)       |
| add_x_82       | DW01_inc       | width=3    | add_250_I4 (HT.v:250)      |
| eq_x_83        | DW_cmp         | width=4    | eq_253_I4 (HT.v:253)       |
| eq_x_84        | DW_cmp         | width=4    | eq_248_I5 (HT.v:248)       |
| add_x_85       | DW01_inc       | width=3    | add_250_I5 (HT.v:250)      |
| eq_x_86        | DW_cmp         | width=4    | eq_253_I5 (HT.v:253)       |
| eq_x_87        | DW_cmp         | width=4    | eq_248_I6 (HT.v:248)       |
| add_x_88       | DW01_inc       | width=3    | add_250_I6 (HT.v:250)      |
| eq_x_89        | DW_cmp         | width=4    | eq_253_I6 (HT.v:253)       |
| eq_x_90        | DW_cmp         | width=4    | eq_248_I7 (HT.v:248)       |
| add_x_91       | DW01_inc       | width=3    | add_250_I7 (HT.v:250)      |
| eq_x_92        | DW_cmp         | width=4    | eq_253_I7 (HT.v:253)       |
| gt_x_126       | DW_cmp         | width=3    | gt_285 (HT.v:285)          |
| sub_x_127      | DW01_dec       | width=3    | sub_288 (HT.v:288)         |
| add_x_128      | DW01_inc       | width=3    | add_295 (HT.v:295)         |
| gt_x_149       | DW_cmp         | width=7    | sort_inst_7/gt_77_S2 (SORT_IP.v:77) |
| gt_x_152       | DW_cmp         | width=7    | sort_inst_7/gt_78_S2 (SORT_IP.v:78) |
| gt_x_155       | DW_cmp         | width=7    | sort_inst_7/gt_79_S2 (SORT_IP.v:79) |
| add_x_197      | DW01_add       | width=2    | C1383 (HT.v:248)           |
|                |                |            | add_255_I2 (HT.v:255)      |
| add_x_198      | DW01_add       | width=3    | C1389 (HT.v:248)           |
|                |                |            | add_255_I3 (HT.v:255)      |
| add_x_199      | DW01_add       | width=3    | C1395 (HT.v:248)           |
|                |                |            | add_255_I4 (HT.v:255)      |
| add_x_200      | DW01_add       | width=3    | C1401 (HT.v:248)           |
|                |                |            | add_255_I5 (HT.v:255)      |
| add_x_201      | DW01_add       | width=3    | C1407 (HT.v:248)           |
|                |                |            | add_255_I6 (HT.v:255)      |
| add_x_202      | DW01_add       | width=3    | C1413 (HT.v:248)           |
|                |                |            | add_255_I7 (HT.v:255)      |
| lte_x_203      | DW_cmp         | width=3    | lte_235 (HT.v:235)         |
|                |                |            | lte_290 (HT.v:290)         |
| gt_x_204       | DW_cmp         | width=9    | sort_inst_7/gt_82 (SORT_IP.v:82) |
           |                |            | sort_inst_7/gt_82_S2 (SORT_IP.v:82) |
| gt_x_205       | DW_cmp         | width=9    | sort_inst_7/gt_83 (SORT_IP.v:83) |
           |                |            | sort_inst_7/gt_83_S2 (SORT_IP.v:83) |
| gt_x_206       | DW_cmp         | width=9    | sort_inst_7/gt_84 (SORT_IP.v:84) |
           |                |            | sort_inst_7/gt_84_S2 (SORT_IP.v:84) |
| gt_x_207       | DW_cmp         | width=9    | sort_inst_7/gt_88 (SORT_IP.v:88) |
           |                |            | sort_inst_7/gt_88_S2 (SORT_IP.v:88) |
| gt_x_208       | DW_cmp         | width=9    | sort_inst_7/gt_90 (SORT_IP.v:90) |
           |                |            | sort_inst_7/gt_90_S2 (SORT_IP.v:90) |
| gt_x_209       | DW_cmp         | width=9    | sort_inst_7/gt_92 (SORT_IP.v:92) |
           |                |            | sort_inst_7/gt_92_S2 (SORT_IP.v:92) |
| gt_x_210       | DW_cmp         | width=9    | sort_inst_7/gt_93 (SORT_IP.v:93) |
           |                |            | sort_inst_7/gt_93_S2 (SORT_IP.v:93) |
| gt_x_211       | DW_cmp         | width=9    | sort_inst_7/gt_94 (SORT_IP.v:94) |
           |                |            | sort_inst_7/gt_94_S2 (SORT_IP.v:94) |
| gt_x_212       | DW_cmp         | width=9    | sort_inst_7/gt_98 (SORT_IP.v:98) |
           |                |            | sort_inst_7/gt_98_S2 (SORT_IP.v:98) |
| gt_x_213       | DW_cmp         | width=9    | sort_inst_7/gt_99 (SORT_IP.v:99) |
           |                |            | sort_inst_7/gt_99_S2 (SORT_IP.v:99) |
| gt_x_214       | DW_cmp         | width=9    | sort_inst_7/gt_103 (SORT_IP.v:103) |
         |                |            | sort_inst_7/gt_103_S2 (SORT_IP.v:103) |
| gt_x_215       | DW_cmp         | width=9    | sort_inst_7/gt_104 (SORT_IP.v:104) |
         |                |            | sort_inst_7/gt_104_S2 (SORT_IP.v:104) |
| gt_x_216       | DW_cmp         | width=9    | sort_inst_7/gt_105 (SORT_IP.v:105) |
         |                |            | sort_inst_7/gt_105_S2 (SORT_IP.v:105) |
| sub_x_125      | DW01_dec       | width=3    | sub_280 (HT.v:280)         |
|                |                |            | sub_293 (HT.v:293)         |
| DP_OP_387J1_122_1498            |            |                            |
|                | DP_OP_387J1_122_1498 |      |                            |
| DP_OP_72_139_8549               |            |                            |
|                | DP_OP_72_139_8549 |         |                            |
| DP_OP_73_140_8549               |            |                            |
|                | DP_OP_73_140_8549 |         |                            |
| DP_OP_80_137_1337               |            |                            |
|                | DP_OP_80_137_1337 |         |                            |
| DP_OP_81_138_1337               |            |                            |
|                | DP_OP_81_138_1337 |         |                            |
| DP_OP_62_135_5538               |            |                            |
|                | DP_OP_62_135_5538 |         |                            |
| DP_OP_63_136_9771               |            |                            |
|                | DP_OP_63_136_9771 |         |                            |
=============================================================================

Datapath Report for DP_OP_387J1_122_1498
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_387J1_122_1498 | add_119 (HT.v:119) add_138 (HT.v:138)               |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 3     |                                          |
| I2    | PI   | Unsigned | 3     |                                          |
| I3    | PI   | Unsigned | 3     |                                          |
| O1    | PO   | Unsigned | 4     | I1 + I2 (HT.v:119)                       |
| O2    | PO   | Unsigned | 5     | O1 + I3 (HT.v:138)                       |
==============================================================================

Datapath Report for DP_OP_72_139_8549
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_72_139_8549    | add_193 (HT.v:193)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 6     |                                          |
| I2    | PI   | Unsigned | 6     |                                          |
| O1    | PO   | Unsigned | 6     | I1 + I2 (HT.v:193)                       |
==============================================================================

Datapath Report for DP_OP_73_140_8549
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_73_140_8549    | add_194 (HT.v:194)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 6     |                                          |
| I2    | PI   | Unsigned | 6     |                                          |
| O1    | PO   | Unsigned | 6     | I1 + I2 (HT.v:194)                       |
==============================================================================

Datapath Report for DP_OP_80_137_1337
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_80_137_1337    | add_208 (HT.v:208)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 6     |                                          |
| I2    | PI   | Unsigned | 6     |                                          |
| O1    | PO   | Unsigned | 6     | I1 + I2 (HT.v:208)                       |
==============================================================================

Datapath Report for DP_OP_81_138_1337
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_81_138_1337    | add_209 (HT.v:209)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 6     |                                          |
| I2    | PI   | Unsigned | 6     |                                          |
| O1    | PO   | Unsigned | 6     | I1 + I2 (HT.v:209)                       |
==============================================================================

Datapath Report for DP_OP_62_135_5538
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_62_135_5538    | add_176 (HT.v:176)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 6     |                                          |
| I2    | PI   | Unsigned | 5     |                                          |
| O1    | PO   | Unsigned | 6     | I1 + I2 (HT.v:176)                       |
==============================================================================

Datapath Report for DP_OP_63_136_9771
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_63_136_9771    | add_177 (HT.v:177)                                  |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 5     |                                          |
| I2    | PI   | Unsigned | 5     |                                          |
| O1    | PO   | Unsigned | 6     | I1 + I2 (HT.v:177)                       |
==============================================================================


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| add_x_1            | DW01_inc         | apparch (area)     |                |
| lte_x_4            | DW_cmp           | apparch (area)     |                |
| lte_x_5            | DW_cmp           | apparch (area)     |                |
| lte_x_6            | DW_cmp           | apparch (area)     |                |
| lte_x_7            | DW_cmp           | apparch (area)     |                |
| lte_x_8            | DW_cmp           | apparch (area)     |                |
| lte_x_9            | DW_cmp           | apparch (area)     |                |
| lte_x_10           | DW_cmp           | apparch (area)     |                |
| lte_x_19           | DW_cmp           | apparch (area)     |                |
| lte_x_20           | DW_cmp           | apparch (area)     |                |
| lte_x_21           | DW_cmp           | apparch (area)     |                |
| lte_x_22           | DW_cmp           | apparch (area)     |                |
| lte_x_23           | DW_cmp           | apparch (area)     |                |
| lte_x_24           | DW_cmp           | apparch (area)     |                |
| add_x_32           | DW01_add         | apparch (area)     |                |
| lte_x_34           | DW_cmp           | apparch (area)     |                |
| lte_x_35           | DW_cmp           | apparch (area)     |                |
| lte_x_36           | DW_cmp           | apparch (area)     |                |
| lte_x_37           | DW_cmp           | apparch (area)     |                |
| lte_x_38           | DW_cmp           | apparch (area)     |                |
| add_x_45           | DW01_add         | apparch (area)     |                |
| add_x_46           | DW01_add         | apparch (area)     |                |
| lte_x_48           | DW_cmp           | apparch (area)     |                |
| lte_x_49           | DW_cmp           | apparch (area)     |                |
| lte_x_50           | DW_cmp           | apparch (area)     |                |
| lte_x_51           | DW_cmp           | apparch (area)     |                |
| lte_x_57           | DW_cmp           | apparch (area)     |                |
| lte_x_58           | DW_cmp           | apparch (area)     |                |
| lte_x_59           | DW_cmp           | apparch (area)     |                |
| lte_x_64           | DW_cmp           | apparch (area)     |                |
| lte_x_65           | DW_cmp           | apparch (area)     |                |
| lte_x_69           | DW_cmp           | apparch (area)     |                |
| eq_x_73            | DW_cmp           | apparch (area)     |                |
| eq_x_74            | DW_cmp           | apparch (area)     |                |
| eq_x_75            | DW_cmp           | apparch (area)     |                |
| add_x_76           | DW01_inc         | apparch (area)     |                |
| eq_x_77            | DW_cmp           | apparch (area)     |                |
| eq_x_78            | DW_cmp           | apparch (area)     |                |
| add_x_79           | DW01_inc         | apparch (area)     |                |
| eq_x_80            | DW_cmp           | apparch (area)     |                |
| eq_x_81            | DW_cmp           | apparch (area)     |                |
| add_x_82           | DW01_inc         | apparch (area)     |                |
| eq_x_83            | DW_cmp           | apparch (area)     |                |
| eq_x_84            | DW_cmp           | apparch (area)     |                |
| add_x_85           | DW01_inc         | apparch (area)     |                |
| eq_x_86            | DW_cmp           | apparch (area)     |                |
| eq_x_87            | DW_cmp           | apparch (area)     |                |
| add_x_88           | DW01_inc         | apparch (area)     |                |
| eq_x_89            | DW_cmp           | apparch (area)     |                |
| eq_x_90            | DW_cmp           | apparch (area)     |                |
| add_x_91           | DW01_inc         | apparch (area)     |                |
| eq_x_92            | DW_cmp           | apparch (area)     |                |
| gt_x_126           | DW_cmp           | apparch (area)     |                |
| sub_x_127          | DW01_dec         | apparch (area)     |                |
| add_x_128          | DW01_inc         | apparch (area)     |                |
| gt_x_149           | DW_cmp           | apparch (area)     |                |
| gt_x_152           | DW_cmp           | apparch (area)     |                |
| gt_x_155           | DW_cmp           | apparch (area)     |                |
| add_x_197          | DW01_add         | apparch (area)     |                |
| add_x_198          | DW01_add         | apparch (area)     |                |
| add_x_199          | DW01_add         | apparch (area)     |                |
| add_x_200          | DW01_add         | apparch (area)     |                |
| add_x_201          | DW01_add         | apparch (area)     |                |
| add_x_202          | DW01_add         | apparch (area)     |                |
| lte_x_203          | DW_cmp           | apparch (area)     |                |
| gt_x_204           | DW_cmp           | apparch (area)     |                |
| gt_x_205           | DW_cmp           | apparch (area)     |                |
| gt_x_206           | DW_cmp           | apparch (area)     |                |
| gt_x_207           | DW_cmp           | apparch (area)     |                |
| gt_x_208           | DW_cmp           | apparch (area)     |                |
| gt_x_209           | DW_cmp           | apparch (area)     |                |
| gt_x_210           | DW_cmp           | apparch (area)     |                |
| gt_x_211           | DW_cmp           | apparch (area)     |                |
| gt_x_212           | DW_cmp           | apparch (area)     |                |
| gt_x_213           | DW_cmp           | apparch (area)     |                |
| gt_x_214           | DW_cmp           | apparch (area)     |                |
| gt_x_215           | DW_cmp           | apparch (area)     |                |
| gt_x_216           | DW_cmp           | apparch (area)     |                |
| sub_x_125          | DW01_dec         | apparch (area)     |                |
| DP_OP_387J1_122_1498                  |                    |                |
|                    | DP_OP_387J1_122_1498 | str (area)     |                |
| DP_OP_72_139_8549  | DP_OP_72_139_8549 | str (area,speed)  |                |
| DP_OP_73_140_8549  | DP_OP_73_140_8549 | str (area,speed)  |                |
| DP_OP_80_137_1337  | DP_OP_80_137_1337 | str (area,speed)  |                |
| DP_OP_81_138_1337  | DP_OP_81_138_1337 | str (area,speed)  |                |
| DP_OP_62_135_5538  | DP_OP_62_135_5538 | str (area,speed)  |                |
| DP_OP_63_136_9771  | DP_OP_63_136_9771 | str (area,speed)  |                |
===============================================================================

1
