 
****************************************
Report : resources
Design : LAB8_DESIGN
Version: T-2022.03
Date   : Mon May  4 13:06:49 2026
****************************************


Resource Report for this hierarchy in file ../01_RTL/LAB8_DESIGN.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_1        | DW_cmp         | width=7    | gte_57 (LAB8_DESIGN.v:57)  |
| add_x_3        | DW01_inc       | width=7    | add_65_S2 (LAB8_DESIGN.v:65) |
| sub_x_5        | DW01_dec       | width=4    | sub_69 (LAB8_DESIGN.v:69)  |
| eq_x_6         | DW_cmp         | width=3    | eq_91 (LAB8_DESIGN.v:91)   |
| eq_x_7         | DW_cmp         | width=3    | eq_92 (LAB8_DESIGN.v:92)   |
| eq_x_8         | DW_cmp         | width=3    | eq_93 (LAB8_DESIGN.v:93)   |
| eq_x_9         | DW_cmp         | width=5    | eq_96_2 (LAB8_DESIGN.v:96) |
| eq_x_10        | DW_cmp         | width=5    | eq_99_2 (LAB8_DESIGN.v:99) |
| eq_x_301       | DW_cmp         | width=2    | eq_224 (LAB8_DESIGN.v:224) |
| eq_x_302       | DW_cmp         | width=7    | eq_225 (LAB8_DESIGN.v:225) |
| lte_x_312      | DW_cmp         | width=7    | lte_247 (LAB8_DESIGN.v:247) |
| add_x_338      | DW01_add       | width=8    | add_373 (LAB8_DESIGN.v:373) |
| add_x_339      | DW01_add       | width=8    | add_374 (LAB8_DESIGN.v:374) |
| add_x_340      | DW01_add       | width=8    | add_375 (LAB8_DESIGN.v:375) |
| add_x_341      | DW01_add       | width=8    | add_376 (LAB8_DESIGN.v:376) |
| gte_x_354      | DW_cmp         | width=7    | gte_58 (LAB8_DESIGN.v:58)  |
|                |                |            | gte_64 (LAB8_DESIGN.v:64)  |
| eq_x_355       | DW_cmp         | width=3    | eq_78 (LAB8_DESIGN.v:78)   |
|                |                |            | eq_94 (LAB8_DESIGN.v:94)   |
|                |                |            | eq_96 (LAB8_DESIGN.v:96)   |
| eq_x_356       | DW_cmp         | width=3    | eq_79 (LAB8_DESIGN.v:79)   |
|                |                |            | eq_99 (LAB8_DESIGN.v:99)   |
| ne_x_357       | DW_cmp         | width=2    | ne_96 (LAB8_DESIGN.v:96)   |
|                |                |            | ne_99 (LAB8_DESIGN.v:99)   |
| eq_x_358       | DW_cmp         | width=2    | eq_138_5 (LAB8_DESIGN.v:138) |
               |                |            | eq_138_5_G2 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_5_G3 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_5_G4 (LAB8_DESIGN.v:138) |
            |                |            | eq_156_2 (LAB8_DESIGN.v:156) |
               |                |            | eq_156_2_G2 (LAB8_DESIGN.v:156) |
            |                |            | eq_156_2_G3 (LAB8_DESIGN.v:156) |
            |                |            | eq_156_2_G4 (LAB8_DESIGN.v:156) |
            |                |            | eq_171_5 (LAB8_DESIGN.v:171) |
               |                |            | eq_171_5_G2 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_5_G3 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_5_G4 (LAB8_DESIGN.v:171) |
            |                |            | eq_189_2 (LAB8_DESIGN.v:189) |
               |                |            | eq_189_2_G2 (LAB8_DESIGN.v:189) |
            |                |            | eq_189_2_G3 (LAB8_DESIGN.v:189) |
            |                |            | eq_189_2_G4 (LAB8_DESIGN.v:189) |
| eq_x_359       | DW_cmp         | width=2    | eq_106 (LAB8_DESIGN.v:106) |
|                |                |            | eq_138_4 (LAB8_DESIGN.v:138) |
               |                |            | eq_138_4_G10 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_4_G11 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_4_G12 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_4_G13 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_4_G14 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_4_G15 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_4_G16 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_4_G2 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_4_G3 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_4_G4 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_4_G5 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_4_G6 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_4_G7 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_4_G8 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_4_G9 (LAB8_DESIGN.v:138) |
            |                |            | eq_156 (LAB8_DESIGN.v:156) |
|                |                |            | eq_156_G10 (LAB8_DESIGN.v:156) |
             |                |            | eq_156_G11 (LAB8_DESIGN.v:156) |
             |                |            | eq_156_G12 (LAB8_DESIGN.v:156) |
             |                |            | eq_156_G13 (LAB8_DESIGN.v:156) |
             |                |            | eq_156_G14 (LAB8_DESIGN.v:156) |
             |                |            | eq_156_G15 (LAB8_DESIGN.v:156) |
             |                |            | eq_156_G16 (LAB8_DESIGN.v:156) |
             |                |            | eq_156_G2 (LAB8_DESIGN.v:156) |
              |                |            | eq_156_G3 (LAB8_DESIGN.v:156) |
              |                |            | eq_156_G4 (LAB8_DESIGN.v:156) |
              |                |            | eq_156_G5 (LAB8_DESIGN.v:156) |
              |                |            | eq_156_G6 (LAB8_DESIGN.v:156) |
              |                |            | eq_156_G7 (LAB8_DESIGN.v:156) |
              |                |            | eq_156_G8 (LAB8_DESIGN.v:156) |
              |                |            | eq_156_G9 (LAB8_DESIGN.v:156) |
              |                |            | eq_171_4 (LAB8_DESIGN.v:171) |
               |                |            | eq_171_4_G10 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_4_G11 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_4_G12 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_4_G13 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_4_G14 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_4_G15 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_4_G16 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_4_G2 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_4_G3 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_4_G4 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_4_G5 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_4_G6 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_4_G7 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_4_G8 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_4_G9 (LAB8_DESIGN.v:171) |
            |                |            | eq_189 (LAB8_DESIGN.v:189) |
|                |                |            | eq_189_G10 (LAB8_DESIGN.v:189) |
             |                |            | eq_189_G11 (LAB8_DESIGN.v:189) |
             |                |            | eq_189_G12 (LAB8_DESIGN.v:189) |
             |                |            | eq_189_G13 (LAB8_DESIGN.v:189) |
             |                |            | eq_189_G14 (LAB8_DESIGN.v:189) |
             |                |            | eq_189_G15 (LAB8_DESIGN.v:189) |
             |                |            | eq_189_G16 (LAB8_DESIGN.v:189) |
             |                |            | eq_189_G2 (LAB8_DESIGN.v:189) |
              |                |            | eq_189_G3 (LAB8_DESIGN.v:189) |
              |                |            | eq_189_G4 (LAB8_DESIGN.v:189) |
              |                |            | eq_189_G5 (LAB8_DESIGN.v:189) |
              |                |            | eq_189_G6 (LAB8_DESIGN.v:189) |
              |                |            | eq_189_G7 (LAB8_DESIGN.v:189) |
              |                |            | eq_189_G8 (LAB8_DESIGN.v:189) |
              |                |            | eq_189_G9 (LAB8_DESIGN.v:189) |
              |                |            | eq_230 (LAB8_DESIGN.v:230) |
|                |                |            | eq_287_3 (LAB8_DESIGN.v:287) |
               |                |            | eq_309_2 (LAB8_DESIGN.v:309) |
               |                |            | eq_315 (LAB8_DESIGN.v:315) |
|                |                |            | eq_319 (LAB8_DESIGN.v:319) |
| eq_x_360       | DW_cmp         | width=4    | eq_138 (LAB8_DESIGN.v:138) |
|                |                |            | eq_138_2 (LAB8_DESIGN.v:138) |
               |                |            | eq_150 (LAB8_DESIGN.v:150) |
|                |                |            | eq_152 (LAB8_DESIGN.v:152) |
|                |                |            | eq_171 (LAB8_DESIGN.v:171) |
|                |                |            | eq_171_2 (LAB8_DESIGN.v:171) |
               |                |            | eq_183 (LAB8_DESIGN.v:183) |
|                |                |            | eq_185 (LAB8_DESIGN.v:185) |
| eq_x_361       | DW_cmp         | width=4    | eq_138_2_G2 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_G2 (LAB8_DESIGN.v:138) |
              |                |            | eq_150_G2 (LAB8_DESIGN.v:150) |
              |                |            | eq_152_G2 (LAB8_DESIGN.v:152) |
              |                |            | eq_171_2_G2 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_G2 (LAB8_DESIGN.v:171) |
              |                |            | eq_183_G2 (LAB8_DESIGN.v:183) |
              |                |            | eq_185_G2 (LAB8_DESIGN.v:185) |
| eq_x_362       | DW_cmp         | width=4    | eq_138_2_G3 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_G3 (LAB8_DESIGN.v:138) |
              |                |            | eq_150_G3 (LAB8_DESIGN.v:150) |
              |                |            | eq_152_G3 (LAB8_DESIGN.v:152) |
              |                |            | eq_171_2_G3 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_G3 (LAB8_DESIGN.v:171) |
              |                |            | eq_183_G3 (LAB8_DESIGN.v:183) |
              |                |            | eq_185_G3 (LAB8_DESIGN.v:185) |
| eq_x_363       | DW_cmp         | width=4    | eq_138_2_G4 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_G4 (LAB8_DESIGN.v:138) |
              |                |            | eq_150_G4 (LAB8_DESIGN.v:150) |
              |                |            | eq_152_G4 (LAB8_DESIGN.v:152) |
              |                |            | eq_171_2_G4 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_G4 (LAB8_DESIGN.v:171) |
              |                |            | eq_183_G4 (LAB8_DESIGN.v:183) |
              |                |            | eq_185_G4 (LAB8_DESIGN.v:185) |
| eq_x_364       | DW_cmp         | width=4    | eq_138_2_G5 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_G5 (LAB8_DESIGN.v:138) |
              |                |            | eq_150_G5 (LAB8_DESIGN.v:150) |
              |                |            | eq_152_G5 (LAB8_DESIGN.v:152) |
              |                |            | eq_171_2_G5 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_G5 (LAB8_DESIGN.v:171) |
              |                |            | eq_183_G5 (LAB8_DESIGN.v:183) |
              |                |            | eq_185_G5 (LAB8_DESIGN.v:185) |
| eq_x_365       | DW_cmp         | width=2    | eq_138_5_G5 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_5_G6 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_5_G7 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_5_G8 (LAB8_DESIGN.v:138) |
            |                |            | eq_156_2_G5 (LAB8_DESIGN.v:156) |
            |                |            | eq_156_2_G6 (LAB8_DESIGN.v:156) |
            |                |            | eq_156_2_G7 (LAB8_DESIGN.v:156) |
            |                |            | eq_156_2_G8 (LAB8_DESIGN.v:156) |
            |                |            | eq_171_5_G5 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_5_G6 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_5_G7 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_5_G8 (LAB8_DESIGN.v:171) |
            |                |            | eq_189_2_G5 (LAB8_DESIGN.v:189) |
            |                |            | eq_189_2_G6 (LAB8_DESIGN.v:189) |
            |                |            | eq_189_2_G7 (LAB8_DESIGN.v:189) |
            |                |            | eq_189_2_G8 (LAB8_DESIGN.v:189) |
| eq_x_366       | DW_cmp         | width=4    | eq_138_2_G6 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_G6 (LAB8_DESIGN.v:138) |
              |                |            | eq_150_G6 (LAB8_DESIGN.v:150) |
              |                |            | eq_152_G6 (LAB8_DESIGN.v:152) |
              |                |            | eq_171_2_G6 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_G6 (LAB8_DESIGN.v:171) |
              |                |            | eq_183_G6 (LAB8_DESIGN.v:183) |
              |                |            | eq_185_G6 (LAB8_DESIGN.v:185) |
| eq_x_367       | DW_cmp         | width=4    | eq_138_2_G7 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_G7 (LAB8_DESIGN.v:138) |
              |                |            | eq_150_G7 (LAB8_DESIGN.v:150) |
              |                |            | eq_152_G7 (LAB8_DESIGN.v:152) |
              |                |            | eq_171_2_G7 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_G7 (LAB8_DESIGN.v:171) |
              |                |            | eq_183_G7 (LAB8_DESIGN.v:183) |
              |                |            | eq_185_G7 (LAB8_DESIGN.v:185) |
| eq_x_368       | DW_cmp         | width=4    | eq_138_2_G8 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_G8 (LAB8_DESIGN.v:138) |
              |                |            | eq_150_G8 (LAB8_DESIGN.v:150) |
              |                |            | eq_152_G8 (LAB8_DESIGN.v:152) |
              |                |            | eq_171_2_G8 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_G8 (LAB8_DESIGN.v:171) |
              |                |            | eq_183_G8 (LAB8_DESIGN.v:183) |
              |                |            | eq_185_G8 (LAB8_DESIGN.v:185) |
| eq_x_369       | DW_cmp         | width=4    | eq_138_2_G9 (LAB8_DESIGN.v:138) |
            |                |            | eq_138_G9 (LAB8_DESIGN.v:138) |
              |                |            | eq_150_G9 (LAB8_DESIGN.v:150) |
              |                |            | eq_152_G9 (LAB8_DESIGN.v:152) |
              |                |            | eq_171_2_G9 (LAB8_DESIGN.v:171) |
            |                |            | eq_171_G9 (LAB8_DESIGN.v:171) |
              |                |            | eq_183_G9 (LAB8_DESIGN.v:183) |
              |                |            | eq_185_G9 (LAB8_DESIGN.v:185) |
| eq_x_370       | DW_cmp         | width=2    | eq_138_5_G10 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_5_G11 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_5_G12 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_5_G9 (LAB8_DESIGN.v:138) |
            |                |            | eq_156_2_G10 (LAB8_DESIGN.v:156) |
           |                |            | eq_156_2_G11 (LAB8_DESIGN.v:156) |
           |                |            | eq_156_2_G12 (LAB8_DESIGN.v:156) |
           |                |            | eq_156_2_G9 (LAB8_DESIGN.v:156) |
            |                |            | eq_171_5_G10 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_5_G11 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_5_G12 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_5_G9 (LAB8_DESIGN.v:171) |
            |                |            | eq_189_2_G10 (LAB8_DESIGN.v:189) |
           |                |            | eq_189_2_G11 (LAB8_DESIGN.v:189) |
           |                |            | eq_189_2_G12 (LAB8_DESIGN.v:189) |
           |                |            | eq_189_2_G9 (LAB8_DESIGN.v:189) |
| eq_x_371       | DW_cmp         | width=4    | eq_138_2_G10 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_G10 (LAB8_DESIGN.v:138) |
             |                |            | eq_150_G10 (LAB8_DESIGN.v:150) |
             |                |            | eq_152_G10 (LAB8_DESIGN.v:152) |
             |                |            | eq_171_2_G10 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_G10 (LAB8_DESIGN.v:171) |
             |                |            | eq_183_G10 (LAB8_DESIGN.v:183) |
             |                |            | eq_185_G10 (LAB8_DESIGN.v:185) |
| eq_x_372       | DW_cmp         | width=4    | eq_138_2_G11 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_G11 (LAB8_DESIGN.v:138) |
             |                |            | eq_150_G11 (LAB8_DESIGN.v:150) |
             |                |            | eq_152_G11 (LAB8_DESIGN.v:152) |
             |                |            | eq_171_2_G11 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_G11 (LAB8_DESIGN.v:171) |
             |                |            | eq_183_G11 (LAB8_DESIGN.v:183) |
             |                |            | eq_185_G11 (LAB8_DESIGN.v:185) |
| eq_x_373       | DW_cmp         | width=4    | eq_138_2_G12 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_G12 (LAB8_DESIGN.v:138) |
             |                |            | eq_150_G12 (LAB8_DESIGN.v:150) |
             |                |            | eq_152_G12 (LAB8_DESIGN.v:152) |
             |                |            | eq_171_2_G12 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_G12 (LAB8_DESIGN.v:171) |
             |                |            | eq_183_G12 (LAB8_DESIGN.v:183) |
             |                |            | eq_185_G12 (LAB8_DESIGN.v:185) |
| eq_x_374       | DW_cmp         | width=4    | eq_138_2_G13 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_G13 (LAB8_DESIGN.v:138) |
             |                |            | eq_150_G13 (LAB8_DESIGN.v:150) |
             |                |            | eq_152_G13 (LAB8_DESIGN.v:152) |
             |                |            | eq_171_2_G13 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_G13 (LAB8_DESIGN.v:171) |
             |                |            | eq_183_G13 (LAB8_DESIGN.v:183) |
             |                |            | eq_185_G13 (LAB8_DESIGN.v:185) |
| eq_x_375       | DW_cmp         | width=2    | eq_138_5_G13 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_5_G14 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_5_G15 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_5_G16 (LAB8_DESIGN.v:138) |
           |                |            | eq_156_2_G13 (LAB8_DESIGN.v:156) |
           |                |            | eq_156_2_G14 (LAB8_DESIGN.v:156) |
           |                |            | eq_156_2_G15 (LAB8_DESIGN.v:156) |
           |                |            | eq_156_2_G16 (LAB8_DESIGN.v:156) |
           |                |            | eq_171_5_G13 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_5_G14 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_5_G15 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_5_G16 (LAB8_DESIGN.v:171) |
           |                |            | eq_189_2_G13 (LAB8_DESIGN.v:189) |
           |                |            | eq_189_2_G14 (LAB8_DESIGN.v:189) |
           |                |            | eq_189_2_G15 (LAB8_DESIGN.v:189) |
           |                |            | eq_189_2_G16 (LAB8_DESIGN.v:189) |
| eq_x_376       | DW_cmp         | width=4    | eq_138_2_G14 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_G14 (LAB8_DESIGN.v:138) |
             |                |            | eq_150_G14 (LAB8_DESIGN.v:150) |
             |                |            | eq_152_G14 (LAB8_DESIGN.v:152) |
             |                |            | eq_171_2_G14 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_G14 (LAB8_DESIGN.v:171) |
             |                |            | eq_183_G14 (LAB8_DESIGN.v:183) |
             |                |            | eq_185_G14 (LAB8_DESIGN.v:185) |
| eq_x_377       | DW_cmp         | width=4    | eq_138_2_G15 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_G15 (LAB8_DESIGN.v:138) |
             |                |            | eq_150_G15 (LAB8_DESIGN.v:150) |
             |                |            | eq_152_G15 (LAB8_DESIGN.v:152) |
             |                |            | eq_171_2_G15 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_G15 (LAB8_DESIGN.v:171) |
             |                |            | eq_183_G15 (LAB8_DESIGN.v:183) |
             |                |            | eq_185_G15 (LAB8_DESIGN.v:185) |
| eq_x_378       | DW_cmp         | width=4    | eq_138_2_G16 (LAB8_DESIGN.v:138) |
           |                |            | eq_138_G16 (LAB8_DESIGN.v:138) |
             |                |            | eq_150_G16 (LAB8_DESIGN.v:150) |
             |                |            | eq_152_G16 (LAB8_DESIGN.v:152) |
             |                |            | eq_171_2_G16 (LAB8_DESIGN.v:171) |
           |                |            | eq_171_G16 (LAB8_DESIGN.v:171) |
             |                |            | eq_183_G16 (LAB8_DESIGN.v:183) |
             |                |            | eq_185_G16 (LAB8_DESIGN.v:185) |
| DP_OP_1061J1_122_9610           |            |                            |
|                | DP_OP_1061J1_122_9610 |     |                            |
=============================================================================

Datapath Report for DP_OP_1061J1_122_9610
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_1061J1_122_9610 | sub_36 (LAB8_DESIGN.v:36)                          |
|                      | add_401 (LAB8_DESIGN.v:401)                         |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 7     |                                          |
| T784  | IFO  | Signed   | 5     | O1[4:0]                                  |
| O1    | PO   | Signed   | 7     | I1 - $unsigned(6'b100010) (LAB8_DESIGN.v:36) |
| O2    | PO   | Unsigned | 5     | T784 + $unsigned(1'b1) (LAB8_DESIGN.v:401) |
==============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'gte_58 (LAB8_DESIGN.v:58) gte_64 (LAB8_DESIGN.v:64)' in design 'LAB8_DESIGN' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'sub_36 (LAB8_DESIGN.v:36)'.  (HDL-120)

Information: Operator associated with resources 'add_373 (LAB8_DESIGN.v:373)' in design 'LAB8_DESIGN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C8201 (LAB8_DESIGN.v:357)'.  (HDL-120)

Information: Operator associated with resources 'add_374 (LAB8_DESIGN.v:374)' in design 'LAB8_DESIGN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C8202 (LAB8_DESIGN.v:358)'.  (HDL-120)

Information: Operator associated with resources 'add_375 (LAB8_DESIGN.v:375)' in design 'LAB8_DESIGN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C8203 (LAB8_DESIGN.v:359)'.  (HDL-120)

Information: Operator associated with resources 'add_376 (LAB8_DESIGN.v:376)' in design 'LAB8_DESIGN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C8204 (LAB8_DESIGN.v:360)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| gte_x_1            | DW_cmp           | apparch (area)     |                |
| add_x_3            | DW01_inc         | apparch (area)     |                |
| sub_x_5            | DW01_dec         | apparch (area)     |                |
| eq_x_6             | DW_cmp           | apparch (area)     |                |
| eq_x_7             | DW_cmp           | apparch (area)     |                |
| eq_x_8             | DW_cmp           | apparch (area)     |                |
| eq_x_9             | DW_cmp           | apparch (area)     |                |
| eq_x_10            | DW_cmp           | apparch (area)     |                |
| eq_x_301           | DW_cmp           | apparch (area)     |                |
| eq_x_302           | DW_cmp           | apparch (area)     |                |
| lte_x_312          | DW_cmp           | apparch (area)     |                |
| add_x_338          | DW01_add         | apparch (area)     |                |
| add_x_339          | DW01_add         | apparch (area)     |                |
| add_x_340          | DW01_add         | apparch (area)     |                |
| add_x_341          | DW01_add         | apparch (area)     |                |
| gte_x_354          | DW_cmp           | apparch (area)     |                |
| eq_x_355           | DW_cmp           | apparch (area)     |                |
| eq_x_356           | DW_cmp           | apparch (area)     |                |
| ne_x_357           | DW_cmp           | apparch (area)     |                |
| eq_x_358           | DW_cmp           | apparch (area)     |                |
| eq_x_359           | DW_cmp           | apparch (area)     |                |
| eq_x_360           | DW_cmp           | apparch (area)     |                |
| eq_x_361           | DW_cmp           | apparch (area)     |                |
| eq_x_362           | DW_cmp           | apparch (area)     |                |
| eq_x_363           | DW_cmp           | apparch (area)     |                |
| eq_x_364           | DW_cmp           | apparch (area)     |                |
| eq_x_365           | DW_cmp           | apparch (area)     |                |
| eq_x_366           | DW_cmp           | apparch (area)     |                |
| eq_x_367           | DW_cmp           | apparch (area)     |                |
| eq_x_368           | DW_cmp           | apparch (area)     |                |
| eq_x_369           | DW_cmp           | apparch (area)     |                |
| eq_x_370           | DW_cmp           | apparch (area)     |                |
| eq_x_371           | DW_cmp           | apparch (area)     |                |
| eq_x_372           | DW_cmp           | apparch (area)     |                |
| eq_x_373           | DW_cmp           | apparch (area)     |                |
| eq_x_374           | DW_cmp           | apparch (area)     |                |
| eq_x_375           | DW_cmp           | apparch (area)     |                |
| eq_x_376           | DW_cmp           | apparch (area)     |                |
| eq_x_377           | DW_cmp           | apparch (area)     |                |
| eq_x_378           | DW_cmp           | apparch (area)     |                |
| DP_OP_1061J1_122_9610                 |                    |                |
|                    | DP_OP_1061J1_122_9610 | str (area)    |                |
===============================================================================

1
