 
****************************************
Report : resources
Design : LAB8_DESIGN
Version: T-2022.03
Date   : Mon May  4 00:11:00 2026
****************************************


Resource Report for this hierarchy in file ../01_RTL/LAB8_DESIGN_wocg.v
=============================================================================
| Cell           | Module         | Parameters | Contained Operations       |
=============================================================================
| gte_x_1        | DW_cmp         | width=7    | gte_49 (LAB8_DESIGN_wocg.v:49) |
| add_x_3        | DW01_inc       | width=7    | add_57_S2 (LAB8_DESIGN_wocg.v:57) |
| sub_x_5        | DW01_dec       | width=4    | sub_61 (LAB8_DESIGN_wocg.v:61) |
| eq_x_6         | DW_cmp         | width=3    | eq_83 (LAB8_DESIGN_wocg.v:83) |
| eq_x_7         | DW_cmp         | width=3    | eq_84 (LAB8_DESIGN_wocg.v:84) |
| eq_x_8         | DW_cmp         | width=3    | eq_85 (LAB8_DESIGN_wocg.v:85) |
| eq_x_9         | DW_cmp         | width=5    | eq_88_2 (LAB8_DESIGN_wocg.v:88) |
| eq_x_10        | DW_cmp         | width=5    | eq_91_2 (LAB8_DESIGN_wocg.v:91) |
| eq_x_301       | DW_cmp         | width=2    | eq_216 (LAB8_DESIGN_wocg.v:216) |
| eq_x_302       | DW_cmp         | width=7    | eq_217 (LAB8_DESIGN_wocg.v:217) |
| lte_x_312      | DW_cmp         | width=7    | lte_239 (LAB8_DESIGN_wocg.v:239) |
| add_x_338      | DW01_add       | width=8    | add_365 (LAB8_DESIGN_wocg.v:365) |
| add_x_339      | DW01_add       | width=8    | add_366 (LAB8_DESIGN_wocg.v:366) |
| add_x_340      | DW01_add       | width=8    | add_367 (LAB8_DESIGN_wocg.v:367) |
| add_x_341      | DW01_add       | width=8    | add_368 (LAB8_DESIGN_wocg.v:368) |
| gte_x_354      | DW_cmp         | width=7    | gte_50 (LAB8_DESIGN_wocg.v:50) |
             |                |            | gte_56 (LAB8_DESIGN_wocg.v:56) |
| eq_x_355       | DW_cmp         | width=3    | eq_70 (LAB8_DESIGN_wocg.v:70) |
              |                |            | eq_86 (LAB8_DESIGN_wocg.v:86) |
              |                |            | eq_88 (LAB8_DESIGN_wocg.v:88) |
| eq_x_356       | DW_cmp         | width=3    | eq_71 (LAB8_DESIGN_wocg.v:71) |
              |                |            | eq_91 (LAB8_DESIGN_wocg.v:91) |
| ne_x_357       | DW_cmp         | width=2    | ne_88 (LAB8_DESIGN_wocg.v:88) |
              |                |            | ne_91 (LAB8_DESIGN_wocg.v:91) |
| eq_x_358       | DW_cmp         | width=2    | eq_148_2 (LAB8_DESIGN_wocg.v:148) |
          |                |            | eq_148_2_G2 (LAB8_DESIGN_wocg.v:148) |
       |                |            | eq_148_2_G3 (LAB8_DESIGN_wocg.v:148) |
       |                |            | eq_148_2_G4 (LAB8_DESIGN_wocg.v:148) |
       |                |            | eq_181_2 (LAB8_DESIGN_wocg.v:181) |
          |                |            | eq_181_2_G2 (LAB8_DESIGN_wocg.v:181) |
       |                |            | eq_181_2_G3 (LAB8_DESIGN_wocg.v:181) |
       |                |            | eq_181_2_G4 (LAB8_DESIGN_wocg.v:181) |
| eq_x_359       | DW_cmp         | width=2    | eq_148 (LAB8_DESIGN_wocg.v:148) |
            |                |            | eq_148_G10 (LAB8_DESIGN_wocg.v:148) |
        |                |            | eq_148_G11 (LAB8_DESIGN_wocg.v:148) |
        |                |            | eq_148_G12 (LAB8_DESIGN_wocg.v:148) |
        |                |            | eq_148_G13 (LAB8_DESIGN_wocg.v:148) |
        |                |            | eq_148_G14 (LAB8_DESIGN_wocg.v:148) |
        |                |            | eq_148_G15 (LAB8_DESIGN_wocg.v:148) |
        |                |            | eq_148_G16 (LAB8_DESIGN_wocg.v:148) |
        |                |            | eq_148_G2 (LAB8_DESIGN_wocg.v:148) |
         |                |            | eq_148_G3 (LAB8_DESIGN_wocg.v:148) |
         |                |            | eq_148_G4 (LAB8_DESIGN_wocg.v:148) |
         |                |            | eq_148_G5 (LAB8_DESIGN_wocg.v:148) |
         |                |            | eq_148_G6 (LAB8_DESIGN_wocg.v:148) |
         |                |            | eq_148_G7 (LAB8_DESIGN_wocg.v:148) |
         |                |            | eq_148_G8 (LAB8_DESIGN_wocg.v:148) |
         |                |            | eq_148_G9 (LAB8_DESIGN_wocg.v:148) |
         |                |            | eq_181 (LAB8_DESIGN_wocg.v:181) |
            |                |            | eq_181_G10 (LAB8_DESIGN_wocg.v:181) |
        |                |            | eq_181_G11 (LAB8_DESIGN_wocg.v:181) |
        |                |            | eq_181_G12 (LAB8_DESIGN_wocg.v:181) |
        |                |            | eq_181_G13 (LAB8_DESIGN_wocg.v:181) |
        |                |            | eq_181_G14 (LAB8_DESIGN_wocg.v:181) |
        |                |            | eq_181_G15 (LAB8_DESIGN_wocg.v:181) |
        |                |            | eq_181_G16 (LAB8_DESIGN_wocg.v:181) |
        |                |            | eq_181_G2 (LAB8_DESIGN_wocg.v:181) |
         |                |            | eq_181_G3 (LAB8_DESIGN_wocg.v:181) |
         |                |            | eq_181_G4 (LAB8_DESIGN_wocg.v:181) |
         |                |            | eq_181_G5 (LAB8_DESIGN_wocg.v:181) |
         |                |            | eq_181_G6 (LAB8_DESIGN_wocg.v:181) |
         |                |            | eq_181_G7 (LAB8_DESIGN_wocg.v:181) |
         |                |            | eq_181_G8 (LAB8_DESIGN_wocg.v:181) |
         |                |            | eq_181_G9 (LAB8_DESIGN_wocg.v:181) |
         |                |            | eq_222 (LAB8_DESIGN_wocg.v:222) |
            |                |            | eq_279_3 (LAB8_DESIGN_wocg.v:279) |
          |                |            | eq_307 (LAB8_DESIGN_wocg.v:307) |
            |                |            | eq_311 (LAB8_DESIGN_wocg.v:311) |
            |                |            | eq_98 (LAB8_DESIGN_wocg.v:98) |
| eq_x_360       | DW_cmp         | width=4    | eq_142 (LAB8_DESIGN_wocg.v:142) |
            |                |            | eq_144 (LAB8_DESIGN_wocg.v:144) |
            |                |            | eq_175 (LAB8_DESIGN_wocg.v:175) |
            |                |            | eq_177 (LAB8_DESIGN_wocg.v:177) |
| eq_x_361       | DW_cmp         | width=4    | eq_142_G2 (LAB8_DESIGN_wocg.v:142) |
         |                |            | eq_144_G2 (LAB8_DESIGN_wocg.v:144) |
         |                |            | eq_175_G2 (LAB8_DESIGN_wocg.v:175) |
         |                |            | eq_177_G2 (LAB8_DESIGN_wocg.v:177) |
| eq_x_362       | DW_cmp         | width=4    | eq_142_G3 (LAB8_DESIGN_wocg.v:142) |
         |                |            | eq_144_G3 (LAB8_DESIGN_wocg.v:144) |
         |                |            | eq_175_G3 (LAB8_DESIGN_wocg.v:175) |
         |                |            | eq_177_G3 (LAB8_DESIGN_wocg.v:177) |
| eq_x_363       | DW_cmp         | width=4    | eq_142_G4 (LAB8_DESIGN_wocg.v:142) |
         |                |            | eq_144_G4 (LAB8_DESIGN_wocg.v:144) |
         |                |            | eq_175_G4 (LAB8_DESIGN_wocg.v:175) |
         |                |            | eq_177_G4 (LAB8_DESIGN_wocg.v:177) |
| eq_x_364       | DW_cmp         | width=4    | eq_142_G5 (LAB8_DESIGN_wocg.v:142) |
         |                |            | eq_144_G5 (LAB8_DESIGN_wocg.v:144) |
         |                |            | eq_175_G5 (LAB8_DESIGN_wocg.v:175) |
         |                |            | eq_177_G5 (LAB8_DESIGN_wocg.v:177) |
| eq_x_365       | DW_cmp         | width=2    | eq_148_2_G5 (LAB8_DESIGN_wocg.v:148) |
       |                |            | eq_148_2_G6 (LAB8_DESIGN_wocg.v:148) |
       |                |            | eq_148_2_G7 (LAB8_DESIGN_wocg.v:148) |
       |                |            | eq_148_2_G8 (LAB8_DESIGN_wocg.v:148) |
       |                |            | eq_181_2_G5 (LAB8_DESIGN_wocg.v:181) |
       |                |            | eq_181_2_G6 (LAB8_DESIGN_wocg.v:181) |
       |                |            | eq_181_2_G7 (LAB8_DESIGN_wocg.v:181) |
       |                |            | eq_181_2_G8 (LAB8_DESIGN_wocg.v:181) |
| eq_x_366       | DW_cmp         | width=4    | eq_142_G6 (LAB8_DESIGN_wocg.v:142) |
         |                |            | eq_144_G6 (LAB8_DESIGN_wocg.v:144) |
         |                |            | eq_175_G6 (LAB8_DESIGN_wocg.v:175) |
         |                |            | eq_177_G6 (LAB8_DESIGN_wocg.v:177) |
| eq_x_367       | DW_cmp         | width=4    | eq_142_G7 (LAB8_DESIGN_wocg.v:142) |
         |                |            | eq_144_G7 (LAB8_DESIGN_wocg.v:144) |
         |                |            | eq_175_G7 (LAB8_DESIGN_wocg.v:175) |
         |                |            | eq_177_G7 (LAB8_DESIGN_wocg.v:177) |
| eq_x_368       | DW_cmp         | width=4    | eq_142_G8 (LAB8_DESIGN_wocg.v:142) |
         |                |            | eq_144_G8 (LAB8_DESIGN_wocg.v:144) |
         |                |            | eq_175_G8 (LAB8_DESIGN_wocg.v:175) |
         |                |            | eq_177_G8 (LAB8_DESIGN_wocg.v:177) |
| eq_x_369       | DW_cmp         | width=4    | eq_142_G9 (LAB8_DESIGN_wocg.v:142) |
         |                |            | eq_144_G9 (LAB8_DESIGN_wocg.v:144) |
         |                |            | eq_175_G9 (LAB8_DESIGN_wocg.v:175) |
         |                |            | eq_177_G9 (LAB8_DESIGN_wocg.v:177) |
| eq_x_370       | DW_cmp         | width=2    | eq_148_2_G10 (LAB8_DESIGN_wocg.v:148) |
      |                |            | eq_148_2_G11 (LAB8_DESIGN_wocg.v:148) |
      |                |            | eq_148_2_G12 (LAB8_DESIGN_wocg.v:148) |
      |                |            | eq_148_2_G9 (LAB8_DESIGN_wocg.v:148) |
       |                |            | eq_181_2_G10 (LAB8_DESIGN_wocg.v:181) |
      |                |            | eq_181_2_G11 (LAB8_DESIGN_wocg.v:181) |
      |                |            | eq_181_2_G12 (LAB8_DESIGN_wocg.v:181) |
      |                |            | eq_181_2_G9 (LAB8_DESIGN_wocg.v:181) |
| eq_x_371       | DW_cmp         | width=4    | eq_142_G10 (LAB8_DESIGN_wocg.v:142) |
        |                |            | eq_144_G10 (LAB8_DESIGN_wocg.v:144) |
        |                |            | eq_175_G10 (LAB8_DESIGN_wocg.v:175) |
        |                |            | eq_177_G10 (LAB8_DESIGN_wocg.v:177) |
| eq_x_372       | DW_cmp         | width=4    | eq_142_G11 (LAB8_DESIGN_wocg.v:142) |
        |                |            | eq_144_G11 (LAB8_DESIGN_wocg.v:144) |
        |                |            | eq_175_G11 (LAB8_DESIGN_wocg.v:175) |
        |                |            | eq_177_G11 (LAB8_DESIGN_wocg.v:177) |
| eq_x_373       | DW_cmp         | width=4    | eq_142_G12 (LAB8_DESIGN_wocg.v:142) |
        |                |            | eq_144_G12 (LAB8_DESIGN_wocg.v:144) |
        |                |            | eq_175_G12 (LAB8_DESIGN_wocg.v:175) |
        |                |            | eq_177_G12 (LAB8_DESIGN_wocg.v:177) |
| eq_x_374       | DW_cmp         | width=4    | eq_142_G13 (LAB8_DESIGN_wocg.v:142) |
        |                |            | eq_144_G13 (LAB8_DESIGN_wocg.v:144) |
        |                |            | eq_175_G13 (LAB8_DESIGN_wocg.v:175) |
        |                |            | eq_177_G13 (LAB8_DESIGN_wocg.v:177) |
| eq_x_375       | DW_cmp         | width=2    | eq_148_2_G13 (LAB8_DESIGN_wocg.v:148) |
      |                |            | eq_148_2_G14 (LAB8_DESIGN_wocg.v:148) |
      |                |            | eq_148_2_G15 (LAB8_DESIGN_wocg.v:148) |
      |                |            | eq_148_2_G16 (LAB8_DESIGN_wocg.v:148) |
      |                |            | eq_181_2_G13 (LAB8_DESIGN_wocg.v:181) |
      |                |            | eq_181_2_G14 (LAB8_DESIGN_wocg.v:181) |
      |                |            | eq_181_2_G15 (LAB8_DESIGN_wocg.v:181) |
      |                |            | eq_181_2_G16 (LAB8_DESIGN_wocg.v:181) |
| eq_x_376       | DW_cmp         | width=4    | eq_142_G14 (LAB8_DESIGN_wocg.v:142) |
        |                |            | eq_144_G14 (LAB8_DESIGN_wocg.v:144) |
        |                |            | eq_175_G14 (LAB8_DESIGN_wocg.v:175) |
        |                |            | eq_177_G14 (LAB8_DESIGN_wocg.v:177) |
| eq_x_377       | DW_cmp         | width=4    | eq_142_G15 (LAB8_DESIGN_wocg.v:142) |
        |                |            | eq_144_G15 (LAB8_DESIGN_wocg.v:144) |
        |                |            | eq_175_G15 (LAB8_DESIGN_wocg.v:175) |
        |                |            | eq_177_G15 (LAB8_DESIGN_wocg.v:177) |
| eq_x_378       | DW_cmp         | width=4    | eq_142_G16 (LAB8_DESIGN_wocg.v:142) |
        |                |            | eq_144_G16 (LAB8_DESIGN_wocg.v:144) |
        |                |            | eq_175_G16 (LAB8_DESIGN_wocg.v:175) |
        |                |            | eq_177_G16 (LAB8_DESIGN_wocg.v:177) |
| DP_OP_803J1_122_9610            |            |                            |
|                | DP_OP_803J1_122_9610 |      |                            |
=============================================================================

Datapath Report for DP_OP_803J1_122_9610
==============================================================================
| Cell                 | Contained Operations                                |
==============================================================================
| DP_OP_803J1_122_9610 | sub_28 (LAB8_DESIGN_wocg.v:28)                      |
|                      | add_393 (LAB8_DESIGN_wocg.v:393)                    |
==============================================================================

==============================================================================
|       |      | Data     |       |                                          |
| Var   | Type | Class    | Width | Expression                               |
==============================================================================
| I1    | PI   | Unsigned | 7     |                                          |
| T655  | IFO  | Signed   | 5     | O1[4:0]                                  |
| O1    | PO   | Signed   | 7     | I1 - $unsigned(6'b100010) (LAB8_DESIGN_wocg.v:28) |
| O2    | PO   | Unsigned | 5     | T655 + $unsigned(1'b1) (LAB8_DESIGN_wocg.v:393) |
==============================================================================


Datapath Extraction Report

Information: Operator associated with resources 'gte_50 (LAB8_DESIGN_wocg.v:50) gte_56 (LAB8_DESIGN_wocg.v:56)' in design 'LAB8_DESIGN' breaks the datapath extraction because there is leakage due to truncation on the fanout of its driver 'sub_28 (LAB8_DESIGN_wocg.v:28)'.  (HDL-120)

Information: Operator associated with resources 'add_365 (LAB8_DESIGN_wocg.v:365)' in design 'LAB8_DESIGN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C7880 (LAB8_DESIGN_wocg.v:349)'.  (HDL-120)

Information: Operator associated with resources 'add_366 (LAB8_DESIGN_wocg.v:366)' in design 'LAB8_DESIGN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C7881 (LAB8_DESIGN_wocg.v:350)'.  (HDL-120)

Information: Operator associated with resources 'add_367 (LAB8_DESIGN_wocg.v:367)' in design 'LAB8_DESIGN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C7882 (LAB8_DESIGN_wocg.v:351)'.  (HDL-120)

Information: Operator associated with resources 'add_368 (LAB8_DESIGN_wocg.v:368)' in design 'LAB8_DESIGN' breaks the datapath extraction because there is leakage due to truncation on its fanout to operator of resources 'C7883 (LAB8_DESIGN_wocg.v:352)'.  (HDL-120)


Implementation Report
===============================================================================
|                    |                  | Current            | Set            |
| Cell               | Module           | Implementation     | Implementation |
===============================================================================
| gte_x_1            | DW_cmp           | apparch (area)     |                |
| add_x_3            | DW01_inc         | apparch (area)     |                |
| sub_x_5            | DW01_dec         | apparch (area)     |                |
| eq_x_6             | DW_cmp           | apparch (area)     |                |
| eq_x_7             | DW_cmp           | apparch (area)     |                |
| eq_x_8             | DW_cmp           | apparch (area)     |                |
| eq_x_9             | DW_cmp           | apparch (area)     |                |
| eq_x_10            | DW_cmp           | apparch (area)     |                |
| eq_x_301           | DW_cmp           | apparch (area)     |                |
| eq_x_302           | DW_cmp           | apparch (area)     |                |
| lte_x_312          | DW_cmp           | apparch (area)     |                |
| add_x_338          | DW01_add         | apparch (area)     |                |
| add_x_339          | DW01_add         | apparch (area)     |                |
| add_x_340          | DW01_add         | apparch (area)     |                |
| add_x_341          | DW01_add         | apparch (area)     |                |
| gte_x_354          | DW_cmp           | apparch (area)     |                |
| eq_x_355           | DW_cmp           | apparch (area)     |                |
| eq_x_356           | DW_cmp           | apparch (area)     |                |
| ne_x_357           | DW_cmp           | apparch (area)     |                |
| eq_x_358           | DW_cmp           | apparch (area)     |                |
| eq_x_359           | DW_cmp           | apparch (area)     |                |
| eq_x_360           | DW_cmp           | apparch (area)     |                |
| eq_x_361           | DW_cmp           | apparch (area)     |                |
| eq_x_362           | DW_cmp           | apparch (area)     |                |
| eq_x_363           | DW_cmp           | apparch (area)     |                |
| eq_x_364           | DW_cmp           | apparch (area)     |                |
| eq_x_365           | DW_cmp           | apparch (area)     |                |
| eq_x_366           | DW_cmp           | apparch (area)     |                |
| eq_x_367           | DW_cmp           | apparch (area)     |                |
| eq_x_368           | DW_cmp           | apparch (area)     |                |
| eq_x_369           | DW_cmp           | apparch (area)     |                |
| eq_x_370           | DW_cmp           | apparch (area)     |                |
| eq_x_371           | DW_cmp           | apparch (area)     |                |
| eq_x_372           | DW_cmp           | apparch (area)     |                |
| eq_x_373           | DW_cmp           | apparch (area)     |                |
| eq_x_374           | DW_cmp           | apparch (area)     |                |
| eq_x_375           | DW_cmp           | apparch (area)     |                |
| eq_x_376           | DW_cmp           | apparch (area)     |                |
| eq_x_377           | DW_cmp           | apparch (area)     |                |
| eq_x_378           | DW_cmp           | apparch (area)     |                |
| DP_OP_803J1_122_9610                  |                    |                |
|                    | DP_OP_803J1_122_9610 | str (area)     |                |
===============================================================================

1
